extern const GeoLayout Wooper_Switch_opt1[];
extern const GeoLayout Wooper_Switch_opt2[];
extern const GeoLayout Wooper_Switch_opt3[];
extern const GeoLayout wooper_geo[];
extern Lights1 Wooper_Main_lights;
extern Lights1 Wooper_face_lights;
extern Lights1 Wooper_Coral_001_lights;
extern Lights1 Wooper_face1_lights;
extern Lights1 Wooper_face2_lights;
extern Lights1 Wooper_face3_lights;
extern u8 Wooper_Wooper_mid_rgba16[];
extern u8 Wooper_face0_rgba16[];
extern u8 Wooper_face1_rgba16[];
extern u8 Wooper_face2_rgba16[];
extern u8 Wooper_face3_rgba16[];
extern Vtx Wooper_Body_mesh_layer_1_vtx_0[134];
extern Gfx Wooper_Body_mesh_layer_1_tri_0[];
extern Vtx Wooper_L_mesh_layer_1_vtx_0[44];
extern Gfx Wooper_L_mesh_layer_1_tri_0[];
extern Vtx Wooper_R_mesh_layer_1_vtx_0[43];
extern Gfx Wooper_R_mesh_layer_1_tri_0[];
extern Vtx Wooper_Head_mesh_layer_1_vtx_0[27];
extern Gfx Wooper_Head_mesh_layer_1_tri_0[];
extern Vtx Wooper_Head_mesh_layer_1_vtx_1[122];
extern Gfx Wooper_Head_mesh_layer_1_tri_1[];
extern Vtx Wooper_Head_mesh_layer_1_vtx_2[95];
extern Gfx Wooper_Head_mesh_layer_1_tri_2[];
extern Vtx Wooper_Tail_mesh_layer_1_vtx_0[67];
extern Gfx Wooper_Tail_mesh_layer_1_tri_0[];
extern Gfx mat_Wooper_Main[];
extern Gfx mat_Wooper_face[];
extern Gfx mat_Wooper_Coral_001[];
extern Gfx mat_Wooper_face1[];
extern Gfx mat_Wooper_face2[];
extern Gfx mat_Wooper_face3[];
extern Gfx Wooper_Body_mesh_layer_1[];
extern Gfx Wooper_L_mesh_layer_1[];
extern Gfx Wooper_R_mesh_layer_1[];
extern Gfx Wooper_Head_mesh_layer_1[];
extern Gfx Wooper_Head_mesh_layer_1_mat_override_face1_0[];
extern Gfx Wooper_Head_mesh_layer_1_mat_override_face2_1[];
extern Gfx Wooper_Head_mesh_layer_1_mat_override_face3_2[];
extern Gfx Wooper_Tail_mesh_layer_1[];
extern Gfx Wooper_material_revert_render_settings[];
