const GeoLayout power_flowers_boomer[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 11, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_asm_switch_root_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_asm_switch_left_leaf_skinned_mesh_layer_1),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -14, 16, -3, -11, 0, 55),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_asm_switch_left_leaf_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_asm_switch_right_leaf_skinned_mesh_layer_1),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 13, 15, -3, -11, 0, -54),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_asm_switch_right_leaf_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_asm_switch_stem_skinned_mesh_layer_1),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, -6, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_asm_switch_stem_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_asm_switch_head_skinned_mesh_layer_1),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 0, -5, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_asm_switch_head_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout power_flowers_asm_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 11, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_root_mesh_layer_1_mat_override_purple_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_left_leaf_skinned_mesh_layer_1_mat_override_purple_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -14, 16, -3, -11, 0, 55),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_left_leaf_mesh_layer_1_mat_override_purple_0),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_right_leaf_skinned_mesh_layer_1_mat_override_purple_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 13, 15, -3, -11, 0, -54),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_right_leaf_mesh_layer_1_mat_override_purple_0),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_stem_skinned_mesh_layer_1_mat_override_purple_0),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, -6, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_stem_mesh_layer_1_mat_override_purple_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_head_skinned_mesh_layer_1_mat_override_purple_0),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 0, -5, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_head_mesh_layer_1_mat_override_purple_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout power_flowers_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 11, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_root_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_left_leaf_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -14, 16, -3, -11, 0, 55),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_left_leaf_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_right_leaf_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 13, 15, -3, -11, 0, -54),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_right_leaf_mesh_layer_1),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_stem_skinned_mesh_layer_1),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 62, 0, -6, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_stem_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_head_skinned_mesh_layer_1),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 21, 0, -5, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, power_flowers_head_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, power_flowers_asm_switch_opt1),
			GEO_BRANCH(1, power_flowers_boomer),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, power_flowers_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
