extern const GeoLayout tree_geo[];
extern Lights1 tree_sm64_leaves_lights;
extern Lights1 tree_sm64_trunk_lights;
extern u8 tree_sm64_leaves_rgba16[];
extern u8 tree_sm64_trunk_rgba16[];
extern Vtx tree_sm64_N64_Tree_mesh_layer_1_vtx_0[97];
extern Gfx tree_sm64_N64_Tree_mesh_layer_1_tri_0[];
extern Vtx tree_sm64_N64_Tree_mesh_layer_1_vtx_1[18];
extern Gfx tree_sm64_N64_Tree_mesh_layer_1_tri_1[];
extern Gfx mat_tree_sm64_leaves[];
extern Gfx mat_tree_sm64_trunk[];
extern Gfx tree_sm64_N64_Tree_mesh_layer_1[];
extern Gfx tree_sm64_material_revert_render_settings[];
