extern const GeoLayout on_off_block_switch_opt1[];
extern const GeoLayout on_off_block_switch_opt2[];
extern const GeoLayout on_off_block_switch_opt3[];
extern const GeoLayout on_off_block_geo[];
extern Lights1 on_off_block_red__pure__lights;
extern Lights1 on_off_block_red__off__lights;
extern Lights1 on_off_block_blue__pure__lights;
extern Lights1 on_off_block_blue__off__lights;
extern u8 on_off_block_full_on_off_red_ci4[];
extern u8 on_off_block_full_on_off_red_ci4_pal_rgba16[];
extern u8 on_off_block_full_on_off_blue_ci4[];
extern u8 on_off_block_full_on_off_blue_ci4_pal_rgba16[];
extern Vtx on_off_block_geo_mesh_layer_1_vtx_0[24];
extern Gfx on_off_block_geo_mesh_layer_1_tri_0[];
extern Gfx mat_on_off_block_red__pure_[];
extern Gfx mat_revert_on_off_block_red__pure_[];
extern Gfx mat_on_off_block_red__off_[];
extern Gfx mat_revert_on_off_block_red__off_[];
extern Gfx mat_on_off_block_blue__pure_[];
extern Gfx mat_revert_on_off_block_blue__pure_[];
extern Gfx mat_on_off_block_blue__off_[];
extern Gfx mat_revert_on_off_block_blue__off_[];
extern Gfx on_off_block_geo_mesh_layer_1[];
extern Gfx on_off_block_geo_mesh_layer_1_mat_override_red__off__0[];
extern Gfx on_off_block_geo_mesh_layer_1_mat_override_blue__pure__1[];
extern Gfx on_off_block_geo_mesh_layer_1_mat_override_blue__off__2[];
extern Gfx on_off_block_material_revert_render_settings[];
