extern const GeoLayout smw_mario_switch_opt1[];
extern const GeoLayout smw_mario_switch_opt2[];
extern const GeoLayout smw_mario_switch_opt3[];
extern const GeoLayout smw_mario_switch_opt4[];
extern const GeoLayout smw_mario_switch_opt5[];
extern const GeoLayout smw_mario_switch_opt6[];
extern const GeoLayout smw_mario_switch_opt7[];
extern const GeoLayout smw_mario_switch_opt8[];
extern const GeoLayout smw_mario_switch_opt9[];
extern const GeoLayout smw_mario_switch_opt10[];
extern const GeoLayout smw_mario_switch_opt11[];
extern const GeoLayout smw_mario_switch_opt12[];
extern const GeoLayout smw_mario_switch_opt13[];
extern const GeoLayout smw_mario_switch_opt14[];
extern const GeoLayout smw_mario_switch_opt15[];
extern const GeoLayout smw_mario_switch_opt16[];
extern const GeoLayout smw_mario_geo[];
extern Lights1 smw_mario_idle_lights;
extern Lights1 smw_mario_pipe_lights;
extern Lights1 smw_mario_back_lights;
extern Lights1 smw_mario_look_up_lights;
extern Lights1 smw_mario_duck_lights;
extern Lights1 smw_mario_walk_1_lights;
extern Lights1 smw_mario_walk_2_lights;
extern Lights1 smw_mario_jump_lights;
extern Lights1 smw_mario_fall_lights;
extern Lights1 smw_mario_run_1_lights;
extern Lights1 smw_mario_run_2_lights;
extern Lights1 smw_mario_run_3_lights;
extern Lights1 smw_mario_run_jump_lights;
extern Lights1 smw_mario_slide_lights;
extern Lights1 smw_mario_skid_lights;
extern Lights1 smw_mario_victory_lights;
extern Lights1 smw_mario_death_lights;
extern u8 smw_mario_Idle_ci4[];
extern u8 smw_mario_Idle_ci4_pal_rgba16[];
extern u8 smw_mario_pipe_ci4[];
extern u8 smw_mario_pipe_ci4_pal_rgba16[];
extern u8 smw_mario_back_ci4[];
extern u8 smw_mario_back_ci4_pal_rgba16[];
extern u8 smw_mario_Look_up_ci4[];
extern u8 smw_mario_Look_up_ci4_pal_rgba16[];
extern u8 smw_mario_duck_ci4[];
extern u8 smw_mario_duck_ci4_pal_rgba16[];
extern u8 smw_mario_walk_1_ci4[];
extern u8 smw_mario_walk_1_ci4_pal_rgba16[];
extern u8 smw_mario_walk_2_ci4[];
extern u8 smw_mario_walk_2_ci4_pal_rgba16[];
extern u8 smw_mario_jump_ci8[];
extern u8 smw_mario_jump_ci8_pal_rgba16[];
extern u8 smw_mario_fall_ci4[];
extern u8 smw_mario_fall_ci4_pal_rgba16[];
extern u8 smw_mario_run_1_ci4[];
extern u8 smw_mario_run_1_ci4_pal_rgba16[];
extern u8 smw_mario_run_2_ci4[];
extern u8 smw_mario_run_2_ci4_pal_rgba16[];
extern u8 smw_mario_run_3_ci4[];
extern u8 smw_mario_run_3_ci4_pal_rgba16[];
extern u8 smw_mario_run_jump_ci4[];
extern u8 smw_mario_run_jump_ci4_pal_rgba16[];
extern u8 smw_mario_slide_ci4[];
extern u8 smw_mario_slide_ci4_pal_rgba16[];
extern u8 smw_mario_skid_ci4[];
extern u8 smw_mario_skid_ci4_pal_rgba16[];
extern u8 smw_mario_victory_ci4[];
extern u8 smw_mario_victory_ci4_pal_rgba16[];
extern u8 smw_mario_dead_ci4[];
extern u8 smw_mario_dead_ci4_pal_rgba16[];
extern Vtx smw_mario_geo_mesh_layer_4_vtx_0[3];
extern Gfx smw_mario_geo_mesh_layer_4_tri_0[];
extern Gfx mat_smw_mario_idle[];
extern Gfx mat_revert_smw_mario_idle[];
extern Gfx mat_smw_mario_pipe[];
extern Gfx mat_revert_smw_mario_pipe[];
extern Gfx mat_smw_mario_back[];
extern Gfx mat_revert_smw_mario_back[];
extern Gfx mat_smw_mario_look_up[];
extern Gfx mat_revert_smw_mario_look_up[];
extern Gfx mat_smw_mario_duck[];
extern Gfx mat_revert_smw_mario_duck[];
extern Gfx mat_smw_mario_walk_1[];
extern Gfx mat_revert_smw_mario_walk_1[];
extern Gfx mat_smw_mario_walk_2[];
extern Gfx mat_revert_smw_mario_walk_2[];
extern Gfx mat_smw_mario_jump[];
extern Gfx mat_revert_smw_mario_jump[];
extern Gfx mat_smw_mario_fall[];
extern Gfx mat_revert_smw_mario_fall[];
extern Gfx mat_smw_mario_run_1[];
extern Gfx mat_revert_smw_mario_run_1[];
extern Gfx mat_smw_mario_run_2[];
extern Gfx mat_revert_smw_mario_run_2[];
extern Gfx mat_smw_mario_run_3[];
extern Gfx mat_revert_smw_mario_run_3[];
extern Gfx mat_smw_mario_run_jump[];
extern Gfx mat_revert_smw_mario_run_jump[];
extern Gfx mat_smw_mario_slide[];
extern Gfx mat_revert_smw_mario_slide[];
extern Gfx mat_smw_mario_skid[];
extern Gfx mat_revert_smw_mario_skid[];
extern Gfx mat_smw_mario_victory[];
extern Gfx mat_revert_smw_mario_victory[];
extern Gfx mat_smw_mario_death[];
extern Gfx mat_revert_smw_mario_death[];
extern Gfx smw_mario_geo_mesh_layer_4[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_pipe_0[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_back_1[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_look_up_2[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_duck_3[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_walk_1_4[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_walk_2_5[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_jump_6[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_fall_7[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_run_1_8[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_run_2_9[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_run_3_10[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_run_jump_11[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_slide_12[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_skid_13[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_victory_14[];
extern Gfx smw_mario_geo_mesh_layer_4_mat_override_death_15[];
extern Gfx smw_mario_material_revert_render_settings[];
