extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern const GeoLayout ccm_area_2_geo[];
extern const GeoLayout ccm_area_2[];
extern const Collision ccm_area_2_collision[];
extern const MacroObject ccm_area_2_macro_objs[];
extern Lights1 ccm_dl_cloud_lights;
extern Lights1 ccm_dl_brick_001_lights;
extern Lights1 ccm_dl_floor_lights;
extern Lights1 ccm_dl_roof_lights;
extern Lights1 ccm_dl_floor_001_lights;
extern Lights1 ccm_dl_roof_001_lights;
extern Lights1 ccm_dl_brick_lights;
extern Lights1 ccm_dl_subscibe_lights;
extern u8 ccm_dl_rr_textures_07000_rgba16_rgba16[];
extern u8 ccm_dl_castle_grounds_textures_01000_rgba16_rgba16[];
extern u8 ccm_dl_castle_grounds_textures_0A000_rgba16_rgba16[];
extern u8 ccm_dl_castle_grounds_textures_07800_rgba16_rgba16[];
extern u8 ccm_dl_castle_grounds_textures_0A000_rgba16_ci8[];
extern u8 ccm_dl_castle_grounds_textures_0A000_rgba16_ci8_pal_rgba16[];
extern u8 ccm_dl_castle_grounds_textures_07800_rgba16_ci8[];
extern u8 ccm_dl_castle_grounds_textures_07800_rgba16_ci8_pal_rgba16[];
extern u8 ccm_dl_castle_grounds_textures_01000_rgba16_ci8[];
extern u8 ccm_dl_castle_grounds_textures_01000_rgba16_ci8_pal_rgba16[];
extern u8 ccm_dl_subscribe_ci4[];
extern u8 ccm_dl_subscribe_ci4_pal_rgba16[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[122];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_1[104];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_2[25];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_3[114];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx ccm_dl_subscribe_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_subscribe_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_subscribe_mesh_layer_1_vtx_1[16];
extern Gfx ccm_dl_subscribe_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_subscribe_mesh_layer_1_vtx_2[16];
extern Gfx ccm_dl_subscribe_mesh_layer_1_tri_2[];
extern Vtx ccm_dl_subscribe_mesh_layer_1_vtx_3[4];
extern Gfx ccm_dl_subscribe_mesh_layer_1_tri_3[];
extern Gfx mat_ccm_dl_cloud[];
extern Gfx mat_ccm_dl_brick_001[];
extern Gfx mat_ccm_dl_floor[];
extern Gfx mat_ccm_dl_roof[];
extern Gfx mat_ccm_dl_floor_001[];
extern Gfx mat_revert_ccm_dl_floor_001[];
extern Gfx mat_ccm_dl_roof_001[];
extern Gfx mat_revert_ccm_dl_roof_001[];
extern Gfx mat_ccm_dl_brick[];
extern Gfx mat_revert_ccm_dl_brick[];
extern Gfx mat_ccm_dl_subscibe[];
extern Gfx mat_revert_ccm_dl_subscibe[];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
extern Gfx ccm_dl_subscribe_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
