#include "src/game/envfx_snow.h"

const GeoLayout Stuffwell_blink_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 14, 32, -2, 0, 0, -90),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_eye_mesh_layer_1_mat_override_eye_mid_close1_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_top2_skinned_mesh_layer_1_mat_override_eye_mid_close1_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_top2_mesh_layer_1_mat_override_eye_mid_close1_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Stuffwell_blink_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 14, 32, -2, 0, 0, -90),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_eye_mesh_layer_1_mat_override_eye_mid_close2_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_top2_skinned_mesh_layer_1_mat_override_eye_mid_close2_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_top2_mesh_layer_1_mat_override_eye_mid_close2_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Stuffwell_blink_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 14, 32, -2, 0, 0, -90),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_eye_mesh_layer_1_mat_override_eye_mid_close3_2),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_top2_skinned_mesh_layer_1_mat_override_eye_mid_close3_2),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_top2_mesh_layer_1_mat_override_eye_mid_close3_2),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Stuffwell_blink_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 14, 32, -2, 0, 0, -90),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_eye_mesh_layer_1_mat_override_eye_closed_3),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_top2_skinned_mesh_layer_1_mat_override_eye_closed_3),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_top2_mesh_layer_1_mat_override_eye_closed_3),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Stuffwell_blink_switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 14, 32, -2, 0, 0, -90),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_eye_mesh_layer_1_mat_override_eye_hurt_4),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_top2_skinned_mesh_layer_1_mat_override_eye_hurt_4),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_top2_mesh_layer_1_mat_override_eye_hurt_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Stuffwell_mouth_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -15, 32, -2, -90, 0, 90),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_mouth_mesh_layer_1_mat_override_mouth_O1_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_Bottom2_skinned_mesh_layer_1_mat_override_mouth_O1_0),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_Bottom2_mesh_layer_1_mat_override_mouth_O1_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Stuffwell_mouth_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -15, 32, -2, -90, 0, 90),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_mouth_mesh_layer_1_mat_override_mouth_O2_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_Bottom2_skinned_mesh_layer_1_mat_override_mouth_O2_1),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_Bottom2_mesh_layer_1_mat_override_mouth_O2_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Stuffwell_mouth_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -15, 32, -2, -90, 0, 90),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_mouth_mesh_layer_1_mat_override_mouth_O3_2),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_Bottom2_skinned_mesh_layer_1_mat_override_mouth_O3_2),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_Bottom2_mesh_layer_1_mat_override_mouth_O3_2),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Stuffwell_mouth_switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -15, 32, -2, -90, 0, 90),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_mouth_mesh_layer_1_mat_override_mouth_n_3),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_Bottom2_skinned_mesh_layer_1_mat_override_mouth_n_3),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_Bottom2_mesh_layer_1_mat_override_mouth_n_3),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Stuffwell_mouth_switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -15, 32, -2, -90, 0, 90),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_mouth_mesh_layer_1_mat_override_mouth_D_4),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_Bottom2_skinned_mesh_layer_1_mat_override_mouth_D_4),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_Bottom2_mesh_layer_1_mat_override_mouth_D_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Stuffwell_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, -180, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -19, 32, 7, 0, -90, 180),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_LeftLeg_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 13, 32, 7, -180, 90, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_RightLeg_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 30, 0, Stuffwell_bottom_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_mid_skinned_mesh_layer_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 29, 0, Stuffwell_mid_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 32, 15, -1, 0, 0, 90),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_mid2_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_eye_skinned_mesh_layer_1),
								GEO_SWITCH_CASE(5, geo_stuffwell_blink),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 14, 32, -2, 0, 0, -90),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_eye_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_top2_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_top2_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, Stuffwell_blink_switch_opt1),
									GEO_BRANCH(1, Stuffwell_blink_switch_opt2),
									GEO_BRANCH(1, Stuffwell_blink_switch_opt3),
									GEO_BRANCH(1, Stuffwell_blink_switch_opt4),
									GEO_BRANCH(1, Stuffwell_blink_switch_opt5),
								GEO_CLOSE_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_mouth_skinned_mesh_layer_1),
								GEO_SWITCH_CASE(5, geo_stuffwell_mouth),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -15, 32, -2, -90, 0, 90),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_mouth_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_Bottom2_skinned_mesh_layer_1),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, Stuffwell_Bottom2_mesh_layer_1),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, Stuffwell_mouth_switch_opt1),
									GEO_BRANCH(1, Stuffwell_mouth_switch_opt2),
									GEO_BRANCH(1, Stuffwell_mouth_switch_opt3),
									GEO_BRANCH(1, Stuffwell_mouth_switch_opt4),
									GEO_BRANCH(1, Stuffwell_mouth_switch_opt5),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_top_skinned_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 28, 0, Stuffwell_top_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, Stuffwell_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
