extern const GeoLayout smw_enemies_small_switch_opt1[];
extern const GeoLayout smw_enemies_small_switch_opt2[];
extern const GeoLayout smw_enemies_small_switch_opt3[];
extern const GeoLayout smw_enemies_small_switch_opt4[];
extern const GeoLayout smw_enemies_small_switch_opt5[];
extern const GeoLayout smw_enemies_small_geo[];
extern Lights1 smw_enemies_small_Goomba_dead_lights;
extern Lights1 smw_enemies_small_Ninji_Dead_lights;
extern u8 smw_enemies_small_Goomba_walk_ci4[];
extern u8 smw_enemies_small_Goomba_walk_ci4_pal_rgba16[];
extern u8 smw_enemies_small_Goomba_Stomped_ci4[];
extern u8 smw_enemies_small_Goomba_Stomped_ci4_pal_rgba16[];
extern u8 smw_enemies_small_Ninji_Jump_ci4[];
extern u8 smw_enemies_small_Ninji_Jump_ci4_pal_rgba16[];
extern u8 smw_enemies_small_Ninji_Ground_ci4[];
extern u8 smw_enemies_small_Ninji_Ground_ci4_pal_rgba16[];
extern Vtx smw_enemies_small_geo_mesh_layer_4_vtx_0[4];
extern Gfx smw_enemies_small_geo_mesh_layer_4_tri_0[];
extern Gfx mat_smw_enemies_small_Goomba_dead[];
extern Gfx mat_revert_smw_enemies_small_Goomba_dead[];
extern Gfx mat_smw_enemies_small_Goomba_stomped[];
extern Gfx mat_revert_smw_enemies_small_Goomba_stomped[];
extern Gfx mat_smw_enemies_small_NIniji_Jump[];
extern Gfx mat_revert_smw_enemies_small_NIniji_Jump[];
extern Gfx mat_smw_enemies_small_Ninji_Ground[];
extern Gfx mat_revert_smw_enemies_small_Ninji_Ground[];
extern Gfx mat_smw_enemies_small_Ninji_Dead[];
extern Gfx mat_revert_smw_enemies_small_Ninji_Dead[];
extern Gfx smw_enemies_small_geo_mesh_layer_4[];
extern Gfx smw_enemies_small_geo_mesh_layer_4_mat_override_Goomba_stomped_0[];
extern Gfx smw_enemies_small_geo_mesh_layer_4_mat_override_Goomba_dead_1[];
extern Gfx smw_enemies_small_geo_mesh_layer_4_mat_override_NIniji_Jump_2[];
extern Gfx smw_enemies_small_geo_mesh_layer_4_mat_override_Ninji_Ground_3[];
extern Gfx smw_enemies_small_geo_mesh_layer_4_mat_override_Ninji_Dead_4[];
extern Gfx smw_enemies_small_material_revert_render_settings[];
