extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_ground_lights;
extern Lights1 bob_dl_quicksand_lights;
extern Lights1 bob_dl_gate_lights;
extern Lights1 bob_dl_stone_lights;
extern Lights1 bob_dl_f3d_material_007_lights;
extern Lights1 bob_dl_sm64_water_mat_lights;
extern u8 bob_dl_bob_textures_08800_rgba16_rgba16[];
extern u8 bob_dl_castle_grounds_textures_01000_rgba16_ci8[];
extern u8 bob_dl_castle_grounds_textures_01000_rgba16_ci8_pal_rgba16[];
extern u8 bob_dl_water_rgba16[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_0[820];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_1[4];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_2[300];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_002_mesh_layer_5_vtx_0[138];
extern Gfx bob_dl_Cube_002_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Water_Box_Mesh_mesh_layer_5_vtx_0[8];
extern Gfx bob_dl_Water_Box_Mesh_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_ground[];
extern Gfx mat_bob_dl_quicksand[];
extern Gfx mat_bob_dl_gate[];
extern Gfx mat_bob_dl_stone[];
extern Gfx mat_revert_bob_dl_stone[];
extern Gfx mat_bob_dl_f3d_material_007[];
extern Gfx mat_bob_dl_sm64_water_mat[];
extern Gfx mat_revert_bob_dl_sm64_water_mat[];
extern Gfx bob_dl_Cube_002_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_5[];
extern Gfx bob_dl_Plane_001_mesh_layer_1[];
extern Gfx bob_dl_Water_Box_Mesh_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
