const GeoLayout Checkpoint_Flag_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_base_mesh_layer_1_mat_override_mario_0),
		GEO_ASM(0, geo_flag_wave),
		GEO_ROTATION_NODE(LAYER_OPAQUE, -90, 0, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag1_mesh_layer_1_mat_override_mario_0),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag2_skinned_mesh_layer_1_mat_override_mario_0),
			GEO_ASM(1, geo_flag_wave),
			GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 0, 0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag2_mesh_layer_1_mat_override_mario_0),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag3_skinned_mesh_layer_1_mat_override_mario_0),
				GEO_ASM(2, geo_flag_wave),
				GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag3_mesh_layer_1_mat_override_mario_0),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag4_skinned_mesh_layer_1_mat_override_mario_0),
					GEO_ASM(3, geo_flag_wave),
					GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag4_mesh_layer_1_mat_override_mario_0),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag5_skinned_mesh_layer_1_mat_override_mario_0),
						GEO_ASM(4, geo_flag_wave),
						GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag5_mesh_layer_1_mat_override_mario_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout Checkpoint_Flag_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_anim_state),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_base_mesh_layer_1),
				GEO_ASM(0, geo_flag_wave),
				GEO_ROTATION_NODE(LAYER_OPAQUE, -90, 0, 0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag1_mesh_layer_1),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag2_skinned_mesh_layer_1),
					GEO_ASM(1, geo_flag_wave),
					GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag2_mesh_layer_1),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag3_skinned_mesh_layer_1),
						GEO_ASM(2, geo_flag_wave),
						GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag3_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag4_skinned_mesh_layer_1),
							GEO_ASM(3, geo_flag_wave),
							GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag4_mesh_layer_1),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag5_skinned_mesh_layer_1),
								GEO_ASM(4, geo_flag_wave),
								GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_flag5_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, Checkpoint_Flag_switch_opt1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, Checkpoint_Flag_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
