extern const GeoLayout smw_blocks_switch_opt1[];
extern const GeoLayout smw_blocks_switch_opt2[];
extern const GeoLayout smw_blocks_switch_opt3[];
extern const GeoLayout smw_blocks_switch_opt4[];
extern const GeoLayout smw_blocks_switch_opt5[];
extern const GeoLayout smw_blocks_switch_opt6[];
extern const GeoLayout smw_blocks_switch_opt7[];
extern const GeoLayout smw_blocks_switch_opt8[];
extern const GeoLayout smw_blocks_switch_opt9[];
extern const GeoLayout smw_blocks_switch_opt10[];
extern const GeoLayout smw_blocks_geo[];
extern Lights1 smw_blocks_red_of_switch_lights;
extern Lights1 smw_blocks_blue_of_switch_lights;
extern u8 smw_blocks_coin_1_ci4[];
extern u8 smw_blocks_coin_1_ci4_pal_rgba16[];
extern u8 smw_blocks_coin_2_ci4[];
extern u8 smw_blocks_coin_2_ci4_pal_rgba16[];
extern u8 smw_blocks_coin_3_ci4[];
extern u8 smw_blocks_coin_3_ci4_pal_rgba16[];
extern u8 smw_blocks_coin_4_ci4[];
extern u8 smw_blocks_coin_4_ci4_pal_rgba16[];
extern u8 smw_blocks_Turn_Block_1_ci4[];
extern u8 smw_blocks_Turn_Block_1_ci4_pal_rgba16[];
extern u8 smw_blocks_Turn_Block_2_ci4[];
extern u8 smw_blocks_Turn_Block_2_ci4_pal_rgba16[];
extern u8 smw_blocks_Turn_Block_3_ci4[];
extern u8 smw_blocks_Turn_Block_3_ci4_pal_rgba16[];
extern u8 smw_blocks_Turn_Block_4_ci4[];
extern u8 smw_blocks_Turn_Block_4_ci4_pal_rgba16[];
extern u8 smw_blocks_message_ci4[];
extern u8 smw_blocks_message_ci4_pal_rgba16[];
extern u8 smw_blocks_on_switch_ci4[];
extern u8 smw_blocks_on_switch_ci4_pal_rgba16[];
extern u8 smw_blocks_off_switch_ci4[];
extern u8 smw_blocks_off_switch_ci4_pal_rgba16[];
extern Vtx smw_blocks_geo_mesh_layer_4_vtx_0[4];
extern Gfx smw_blocks_geo_mesh_layer_4_tri_0[];
extern Gfx mat_smw_blocks_coin_1[];
extern Gfx mat_revert_smw_blocks_coin_1[];
extern Gfx mat_smw_blocks_coin_2[];
extern Gfx mat_revert_smw_blocks_coin_2[];
extern Gfx mat_smw_blocks_coin_3[];
extern Gfx mat_revert_smw_blocks_coin_3[];
extern Gfx mat_smw_blocks_coin_4[];
extern Gfx mat_revert_smw_blocks_coin_4[];
extern Gfx mat_smw_blocks_turn_1[];
extern Gfx mat_revert_smw_blocks_turn_1[];
extern Gfx mat_smw_blocks_turn_2[];
extern Gfx mat_revert_smw_blocks_turn_2[];
extern Gfx mat_smw_blocks_turn_3[];
extern Gfx mat_revert_smw_blocks_turn_3[];
extern Gfx mat_smw_blocks_turn_4[];
extern Gfx mat_revert_smw_blocks_turn_4[];
extern Gfx mat_smw_blocks_Message[];
extern Gfx mat_revert_smw_blocks_Message[];
extern Gfx mat_smw_blocks_red_of_switch[];
extern Gfx mat_revert_smw_blocks_red_of_switch[];
extern Gfx mat_smw_blocks_blue_of_switch[];
extern Gfx mat_revert_smw_blocks_blue_of_switch[];
extern Gfx smw_blocks_geo_mesh_layer_4[];
extern Gfx smw_blocks_geo_mesh_layer_4_mat_override_coin_2_0[];
extern Gfx smw_blocks_geo_mesh_layer_4_mat_override_coin_3_1[];
extern Gfx smw_blocks_geo_mesh_layer_4_mat_override_coin_4_2[];
extern Gfx smw_blocks_geo_mesh_layer_4_mat_override_turn_1_3[];
extern Gfx smw_blocks_geo_mesh_layer_4_mat_override_turn_2_4[];
extern Gfx smw_blocks_geo_mesh_layer_4_mat_override_turn_3_5[];
extern Gfx smw_blocks_geo_mesh_layer_4_mat_override_turn_4_6[];
extern Gfx smw_blocks_geo_mesh_layer_4_mat_override_Message_7[];
extern Gfx smw_blocks_geo_mesh_layer_4_mat_override_red_of_switch_8[];
extern Gfx smw_blocks_geo_mesh_layer_4_mat_override_blue_of_switch_9[];
extern Gfx smw_blocks_material_revert_render_settings[];
