extern const GeoLayout smw_particles_switch_opt1[];
extern const GeoLayout smw_particles_switch_opt2[];
extern const GeoLayout smw_particles_switch_opt3[];
extern const GeoLayout smw_particles_switch_opt4[];
extern const GeoLayout smw_particles_switch_opt5[];
extern const GeoLayout smw_particles_switch_opt6[];
extern const GeoLayout smw_particles_switch_opt7[];
extern const GeoLayout smw_particles_geo[];
extern Lights1 smw_particles_Poof_1_lights;
extern Lights1 smw_particles_Poof_2_lights;
extern Lights1 smw_particles_Poof_3_layer4_lights;
extern Lights1 smw_particles_Poof_4_lights;
extern u8 smw_particles_kick_ia4[];
extern u8 smw_particles_poof_1_ia4[];
extern u8 smw_particles_poof_2_ia4[];
extern u8 smw_particles_poof_3_ia4[];
extern u8 smw_particles_poof_4_ia4[];
extern u8 smw_particles_star_ci4[];
extern u8 smw_particles_star_ci4_pal_rgba16[];
extern u8 smw_particles_shatter_1_ci4[];
extern u8 smw_particles_shatter_1_ci4_pal_rgba16[];
extern u8 smw_particles_shatter_2_ci4[];
extern u8 smw_particles_shatter_2_ci4_pal_rgba16[];
extern Vtx smw_particles_geo_mesh_layer_4_vtx_0[4];
extern Gfx smw_particles_geo_mesh_layer_4_tri_0[];
extern Gfx mat_smw_particles_Kick[];
extern Gfx mat_revert_smw_particles_Kick[];
extern Gfx mat_smw_particles_Poof_1[];
extern Gfx mat_revert_smw_particles_Poof_1[];
extern Gfx mat_smw_particles_Poof_2[];
extern Gfx mat_revert_smw_particles_Poof_2[];
extern Gfx mat_smw_particles_Poof_3_layer4[];
extern Gfx mat_revert_smw_particles_Poof_3_layer4[];
extern Gfx mat_smw_particles_Poof_4[];
extern Gfx mat_revert_smw_particles_Poof_4[];
extern Gfx mat_smw_particles_star[];
extern Gfx mat_revert_smw_particles_star[];
extern Gfx mat_smw_particles_shatter_1[];
extern Gfx mat_revert_smw_particles_shatter_1[];
extern Gfx mat_smw_particles_shatter_2[];
extern Gfx mat_revert_smw_particles_shatter_2[];
extern Gfx smw_particles_geo_mesh_layer_4[];
extern Gfx smw_particles_geo_mesh_layer_4_mat_override_Poof_1_0[];
extern Gfx smw_particles_geo_mesh_layer_4_mat_override_Poof_2_1[];
extern Gfx smw_particles_geo_mesh_layer_4_mat_override_Poof_3_2[];
extern Gfx smw_particles_geo_mesh_layer_4_mat_override_Poof_4_3[];
extern Gfx smw_particles_geo_mesh_layer_4_mat_override_star_4[];
extern Gfx smw_particles_geo_mesh_layer_4_mat_override_shatter_1_5[];
extern Gfx smw_particles_geo_mesh_layer_4_mat_override_shatter_2_6[];
extern Gfx smw_particles_material_revert_render_settings[];
